version: '3'

services:
  employees-db:
    image: postgres
    ports:
      - 5433:5432
    environment:
        POSTGRES_DB: "iss_education"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_USER: "postgres"